DROP DATABASE IF EXISTS recargasatc;
CREATE DATABASE recargasatc;
USE recargasatc;
CREATE TABLE empresa
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    activo bool not null
);
CREATE TABLE acceso_empresa
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	wsdl VARCHAR(200) NOT NULL,
    usuario VARCHAR(200) NOT NULL,
    pass VARCHAR(200) NOT NULL,
    clave_operador VARCHAR(100) NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE
);
CREATE TABLE administrador
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE
);
CREATE TABLE permiso
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tipo VARCHAR(50)
);
CREATE TABLE permiso_administrador
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(200) NOT NULL,
    pass VARCHAR(200) NOT NULL,
    activo BOOL NOT NULL,
    administrador_id INT UNSIGNED NOT NULL REFERENCES administrador.id ON UPDATE CASCADE,
    permiso_id INT UNSIGNED NOT NULL REFERENCES permiso.id ON UPDATE CASCADE
);
CREATE TABLE cliente
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    telefono VARCHAR(200) NOT NULL,
    email VARCHAR(50),
    activo BOOL NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE
);
CREATE TABLE permiso_cliente
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(200) NOT NULL,
    pass VARCHAR(200) NOT NULL,
    activo BOOL NOT NULL,
    cliente_id INT UNSIGNED NOT NULL REFERENCES cliente.id ON UPDATE CASCADE
);
CREATE TABLE registro_login
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fecha DATETIME NOT NULL,
    cliente_id INT UNSIGNED NOT NULL REFERENCES cliente.id ON UPDATE CASCADE
);
CREATE TABLE carrier
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
    activo bool not null
);
CREATE TABLE empresa_carrier
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE,
    carrier_id INT UNSIGNED NOT NULL REFERENCES carrier.id ON UPDATE CASCADE
);
CREATE TABLE recarga_carrier
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	monto INT UNSIGNED NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE,
    carrier_id INT UNSIGNED NOT NULL REFERENCES carrier.id ON UPDATE CASCADE
);
CREATE TABLE numero
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	folio VARCHAR(30) NOT NULL,
    digitos VARCHAR(10) NOT NULL,
	fecha DATETIME NOT NULL,
    monto INT UNSIGNED NOT NULL,
    carrier_id INT UNSIGNED NOT NULL REFERENCES carrier.id ON UPDATE CASCADE,
    cliente_id INT UNSIGNED NOT NULL REFERENCES cliente.id ON UPDATE CASCADE
    
);
CREATE TABLE activado
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cantidad INT UNSIGNED NOT NULL,
    folio VARCHAR(50) NOT NULL,
    idRecargas VARCHAR(50)NOT NULL,
	fecha DATETIME NOT NULL,
    estado BOOL NOT NULL,
    numero_id INT UNSIGNED NOT NULL REFERENCES numero.id ON UPDATE CASCADE
);
CREATE TABLE notificaciones
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
    activo BOOL NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE
);
CREATE TABLE alerta_notificaciones
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	activo BOOL NOT NULL,
    notificaciones_id INT UNSIGNED NOT NULL REFERENCES notificaciones.id ON UPDATE CASCADE
);
CREATE TABLE punto_venta
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tipo VARCHAR(30) NOT NULL,
    activo BOOL NOT NULL,
    empresa_id INT UNSIGNED NOT NULL REFERENCES empresa.id ON UPDATE CASCADE
);
CREATE TABLE clave_cliente
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	numero VARCHAR(10) NOT NULL,
    activo BOOL NOT NULL,
    cliente_id INT UNSIGNED NOT NULL REFERENCES cliente.id ON UPDATE CASCADE,
    puntoventa_id INT UNSIGNED NOT NULL REFERENCES punto_venta.id ON UPDATE CASCADE
);
CREATE TABLE log_error
(	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fecha DATETIME NOT NULL,
    folioCliente varchar(50) NOT NULL,
    topUpID INT not null,
    errorCode INT not null,
    errorMessage VARCHAR(100),
    numero_id INT UNSIGNED NOT NULL REFERENCES numero.id ON UPDATE CASCADE
);
INSERT INTO permiso(tipo)VALUES('Normal');
INSERT INTO permiso(tipo)VALUES('Administrador');
INSERT INTO permiso(tipo)VALUES('Super Administrador');
INSERT INTO permiso(tipo)VALUES('Ventas');

INSERT INTO administrador(nombre,empresa_id)VALUES('Principal',1);
INSERT INTO permiso_administrador(nickname,pass,activo,administrador_id,permiso_id)
VALUES('Principal','M989at+tjQxHNT2JVchRo6q+B4qklbS1M3ThVcUv2oA=',true,1,3);